site_name: "Рашевский_Вячеслав_K33402"
nav:
  - "№1: Реализация серверного приложения FastAPI.":
      - index.md
      - lab.md
      - leetcode.md
  - "№2: Потоки. Процессы. Асинхронность.":
      - lab2.md
      - leetcode2.md